### ISSUE TITLE
ModernBB 3.7 "Blue" Shiplist

### ISSUE THREAD

**Issue by Studio384** [ModernBB/Luna#993]
ModernBB 3.7 is a small release with a couple of new features, through it majorly focusses on fixing bugs and updating components like Bootstrap, jQuery and Font Awesome to the latest and greatest - and most secure - versions.

# Tickets

## Features
- [x] #1082 The editor now acts smarter when including tags.
- [x] #1083 There has a "Back to top" link been added to the footer.

## Components
- [x] #1084 Update Bootstrap version 3.3.1 to version 3.3.2.
- [x] #1085 Update jQuery version 2.1.1 to version 2.1.3.
- [x] #1086 Update Font Awesome version 4.2.0 to version 4.3.0.

## Security
- [x] #1087 You now get a warning when the install.php file exists.

## Styles
- [x] #1088 The Luna style has been improved.
- [x] #1089 Multiple improvements to styles.

## Bugfixes
- [x] #1003 Remove setting of values in quickpostform.
- [x] #1010 Fix for the submit button of the "Request password".
- [x] #1027 New users now have a timezone included in their account by default.
- [x] #1064 A security vulnerability has been fixed.
